'use strict';

/**
 * Schedule arithmetic, and the generator for SCHEDULE.md.
 *
 * Canberra is `Australia/Sydney`, which observes daylight saving. The offset is
 * +10:00 for most of the year and +11:00 from the first Sunday in October to the
 * first Sunday in April.
 *
 * So a UTC time must be computed against the offset in effect **on the posting
 * date**, not today's. Hand-computing this works until it doesn't, and when it
 * fails it posts at the wrong hour, in public, with no undo. Nobody does it by
 * hand; this file does it.
 *
 *   node social/schedule.js                        regenerate SCHEDULE.md
 *   node social/schedule.js --to-utc "2026-10-19 09:00"
 *
 * SCHEDULE.md is GENERATED. Never hand-edit it — regenerate it.
 */

const fs = require('fs');
const path = require('path');

const ZONE = 'Australia/Sydney';
const QUEUE_DIR = path.join(__dirname, 'queue');
const OUT_FILE = path.join(__dirname, 'SCHEDULE.md');

/** The zone's offset from UTC, in milliseconds, at a given instant. */
function offsetAt(instantMs, zone = ZONE) {
  const dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: zone,
    hour12: false,
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
  });
  const p = {};
  for (const part of dtf.formatToParts(new Date(instantMs))) p[part.type] = part.value;
  const asIfUtc = Date.UTC(+p.year, +p.month - 1, +p.day, +p.hour % 24, +p.minute, +p.second);
  return asIfUtc - instantMs;
}

/**
 * Convert a wall-clock time in the zone to a UTC Date.
 *
 * Solved iteratively: the offset depends on the instant, and the instant depends
 * on the offset. Two passes settle it everywhere except inside a DST transition,
 * and a third covers that.
 */
function zonedToUtc(year, month, day, hour = 0, minute = 0, zone = ZONE) {
  const naive = Date.UTC(year, month - 1, day, hour, minute, 0);
  let instant = naive;
  for (let i = 0; i < 3; i += 1) instant = naive - offsetAt(instant, zone);
  return new Date(instant);
}

/** "2026-10-19 09:00" or "2026-10-19T09:00" -> Date (UTC instant). */
function parseLocal(text, zone = ZONE) {
  const m = String(text).trim().match(/^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})$/);
  if (!m) throw new Error(`Expected "YYYY-MM-DD HH:MM", got "${text}"`);
  return zonedToUtc(+m[1], +m[2], +m[3], +m[4], +m[5], zone);
}

/** Render a UTC instant back as local wall-clock, for display. */
function formatLocal(date, zone = ZONE) {
  const dtf = new Intl.DateTimeFormat('en-AU', {
    timeZone: zone, hour12: false,
    weekday: 'short', day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
  });
  return dtf.format(date).replace(',', '');
}

const offsetLabel = (date, zone = ZONE) => {
  const mins = offsetAt(date.getTime(), zone) / 60000;
  const sign = mins < 0 ? '-' : '+';
  const abs = Math.abs(mins);
  return `${sign}${String(Math.floor(abs / 60)).padStart(2, '0')}:${String(abs % 60).padStart(2, '0')}`;
};

// ---------------------------------------------------------------------------
// SCHEDULE.md
// ---------------------------------------------------------------------------

function readQueue(queueDir = QUEUE_DIR) {
  if (!fs.existsSync(queueDir)) return [];
  return fs.readdirSync(queueDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => path.join(queueDir, e.name))
    .filter((dir) => fs.existsSync(path.join(dir, 'publish.json')))
    .map((dir) => ({ slug: path.basename(dir), pkg: JSON.parse(fs.readFileSync(path.join(dir, 'publish.json'), 'utf8')) }))
    .sort((a, b) => String(a.pkg.scheduled_utc || '').localeCompare(String(b.pkg.scheduled_utc || '')));
}

function render(entries, { now = new Date() } = {}) {
  const lines = [];
  lines.push('# Schedule');
  lines.push('');
  lines.push('<!-- GENERATED by social/schedule.js. Do not hand-edit — regenerate. -->');
  lines.push('');
  lines.push(`Generated ${now.toISOString().slice(0, 16).replace('T', ' ')} UTC · zone \`${ZONE}\``);
  lines.push('');

  if (entries.length === 0) {
    lines.push('_The queue is empty._');
  } else {
    lines.push('| Local (Canberra) | Offset | UTC | Status | Approved by | Pillar | Package |');
    lines.push('|---|---|---|---|---|---|---|');
    for (const { slug, pkg } of entries) {
      const utc = pkg.scheduled_utc ? new Date(pkg.scheduled_utc) : null;
      const valid = utc && !Number.isNaN(utc.getTime());
      lines.push([
        '',
        valid ? formatLocal(utc) : '⚠ none',
        valid ? offsetLabel(utc) : '—',
        valid ? utc.toISOString().slice(0, 16).replace('T', ' ') : '—',
        pkg.status || '?',
        pkg.approved_by || '—',
        pkg.pillar || '—',
        `\`${slug}\``,
        '',
      ].join(' | ').trim());
    }
  }

  lines.push('');
  lines.push('## Why this file is generated');
  lines.push('');
  lines.push('Canberra observes daylight saving: `+10:00` most of the year, `+11:00` from');
  lines.push('the first Sunday in October to the first Sunday in April. A UTC time has to be');
  lines.push('computed against the offset in effect **on the posting date**, not today\'s.');
  lines.push('');
  lines.push('Hand-computing it works until it does not, and the failure mode is posting at');
  lines.push('the wrong hour, in public, with no undo. So the offset column above is derived,');
  lines.push('never typed, and this file is regenerated rather than edited.');
  lines.push('');
  lines.push('## Cron');
  lines.push('');
  lines.push('GitHub Actions cron is not the schedule you ask for. On a private repository');
  lines.push('`*/15` has been measured at a median gap of 66 minutes and as much as 162. So');
  lines.push('the workflow runs **hourly**, is set 30 minutes before the intended slot, and');
  lines.push('carries a `push` trigger so an empty commit can nudge a late run. Publishing is');
  lines.push('idempotent, which is what makes nudging safe.');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function generate({ queueDir = QUEUE_DIR, outFile = OUT_FILE, now = new Date() } = {}) {
  const text = render(readQueue(queueDir), { now });
  fs.writeFileSync(outFile, text);
  return text;
}

module.exports = { ZONE, offsetAt, zonedToUtc, parseLocal, formatLocal, offsetLabel, readQueue, render, generate };

if (require.main === module) {
  const argv = process.argv.slice(2);
  const i = argv.indexOf('--to-utc');
  if (i !== -1) {
    const local = argv[i + 1];
    const utc = parseLocal(local);
    console.log(`${local} ${ZONE} (${offsetLabel(utc)})`);
    console.log(`  -> ${utc.toISOString()}`);
  } else {
    generate();
    console.log(`Wrote ${path.relative(process.cwd(), OUT_FILE)}`);
  }
}
