'use strict';

/**
 * Tests for the two scripts that guard the queue.
 *
 *   node --test social/test.js
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const schedule = require('./schedule');
const imagecheck = require('./imagecheck');

// ---------------------------------------------------------------------------
// Daylight saving — the failure that posts at the wrong hour with no undo
// ---------------------------------------------------------------------------

test('9am Canberra in September is +10:00 (AEST)', () => {
  const utc = schedule.parseLocal('2026-09-19 09:00');
  assert.equal(utc.toISOString(), '2026-09-18T23:00:00.000Z');
  assert.equal(schedule.offsetLabel(utc), '+10:00');
});

test('9am Canberra in November is +11:00 (AEDT)', () => {
  const utc = schedule.parseLocal('2026-11-19 09:00');
  assert.equal(utc.toISOString(), '2026-11-18T22:00:00.000Z');
  assert.equal(schedule.offsetLabel(utc), '+11:00');
});

test('the offset changes across the October DST boundary, not on a fixed rule', () => {
  // DST begins on the first Sunday in October. Same wall-clock time, two days
  // apart, is two different UTC instants — this is the case a hand-computed
  // conversion gets wrong.
  const before = schedule.parseLocal('2026-10-03 09:00');
  const after = schedule.parseLocal('2026-10-05 09:00');
  assert.equal(schedule.offsetLabel(before), '+10:00');
  assert.equal(schedule.offsetLabel(after), '+11:00');
  assert.equal(before.toISOString(), '2026-10-02T23:00:00.000Z');
  assert.equal(after.toISOString(), '2026-10-04T22:00:00.000Z');
});

test('the offset changes back across the April boundary', () => {
  assert.equal(schedule.offsetLabel(schedule.parseLocal('2027-04-03 09:00')), '+11:00');
  assert.equal(schedule.offsetLabel(schedule.parseLocal('2027-04-05 09:00')), '+10:00');
});

test('a round trip returns the same wall clock in both halves of the year', () => {
  for (const local of ['2026-09-19 09:00', '2026-12-19 09:00']) {
    const utc = schedule.parseLocal(local);
    assert.match(schedule.formatLocal(utc), /09:00/, `${local} did not round-trip`);
  }
});

test('a malformed local time is rejected rather than guessed at', () => {
  assert.throws(() => schedule.parseLocal('19/09/2026 9am'), /Expected "YYYY-MM-DD HH:MM"/);
});

// ---------------------------------------------------------------------------
// SCHEDULE.md is generated
// ---------------------------------------------------------------------------

test('SCHEDULE.md carries the do-not-edit marker and derives the offset', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-sched-'));
  const pkgDir = path.join(dir, '2026-11-19-x');
  fs.mkdirSync(pkgDir);
  fs.writeFileSync(path.join(pkgDir, 'publish.json'), JSON.stringify({
    status: 'draft', scheduled_utc: '2026-11-18T22:00:00Z', pillar: 'home', approved_by: null,
  }));
  const out = path.join(dir, 'SCHEDULE.md');
  const text = schedule.generate({ queueDir: dir, outFile: out, now: new Date('2026-09-17T00:00:00Z') });
  assert.match(text, /GENERATED by social\/schedule\.js/);
  assert.match(text, /\+11:00/);
  assert.ok(fs.existsSync(out));
});

// ---------------------------------------------------------------------------
// source_images: three states that must stay three states
// ---------------------------------------------------------------------------

const entry = (slug, source_images) => {
  const pkg = { status: 'draft' };
  if (source_images !== undefined) pkg.source_images = source_images;
  return { slug, pkg };
};

test('two packages sharing a source are caught', () => {
  const res = imagecheck.check([
    entry('a', ['kitchen table flowers']),
    entry('b', ['kitchen table flowers']),
  ]);
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'duplicate');
});

test('an absent source_images is reported, not silently treated as empty', () => {
  const res = imagecheck.check([entry('a', undefined)]);
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'unrecorded');
  assert.match(res.problems[0].message, /not the same as \[\]/);
});

test('an empty source_images passes — a type tile genuinely has no source', () => {
  const res = imagecheck.check([entry('a', []), entry('b', [])]);
  assert.equal(res.ok, true);
  assert.equal(res.typeTiles, 2);
});

test('the same photograph under two paths or extensions is still one source', () => {
  // The library holds the same file in two Drive folders, and the catalogue
  // holds one design as two files. Keyed on a path, both slip through.
  const res = imagecheck.check([
    entry('a', ['Adelaide/PRINT-HI-5072_115.jpg']),
    entry('b', ['Photos for marketing/print-hi-5072_115.JPG']),
  ]);
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'duplicate');
});

test('a source repeated inside one package is caught', () => {
  const res = imagecheck.check([entry('a', ['x', 'x'])]);
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'repeat-within');
});

test('a clean queue of distinct sources passes', () => {
  const res = imagecheck.check([
    entry('a', ['kitchen table flowers']),
    entry('b', ['P20TS25042']),
    entry('c', []),
  ]);
  assert.equal(res.ok, true);
  assert.equal(res.distinctSources, 2);
  assert.equal(res.typeTiles, 1);
});

test('source_images that is not an array is rejected', () => {
  const res = imagecheck.check([entry('a', 'kitchen table flowers')]);
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'malformed');
});
