'use strict';

/**
 * Tests for the two scripts that guard the queue.
 *
 *   node --test social/test.js
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const schedule = require('./schedule');
const imagecheck = require('./imagecheck');

// ---------------------------------------------------------------------------
// Daylight saving — the failure that posts at the wrong hour with no undo
// ---------------------------------------------------------------------------

test('9am Canberra in September is +10:00 (AEST)', () => {
  const utc = schedule.parseLocal('2026-09-19 09:00');
  assert.equal(utc.toISOString(), '2026-09-18T23:00:00.000Z');
  assert.equal(schedule.offsetLabel(utc), '+10:00');
});

test('9am Canberra in November is +11:00 (AEDT)', () => {
  const utc = schedule.parseLocal('2026-11-19 09:00');
  assert.equal(utc.toISOString(), '2026-11-18T22:00:00.000Z');
  assert.equal(schedule.offsetLabel(utc), '+11:00');
});

test('the offset changes across the October DST boundary, not on a fixed rule', () => {
  // DST begins on the first Sunday in October. Same wall-clock time, two days
  // apart, is two different UTC instants — this is the case a hand-computed
  // conversion gets wrong.
  const before = schedule.parseLocal('2026-10-03 09:00');
  const after = schedule.parseLocal('2026-10-05 09:00');
  assert.equal(schedule.offsetLabel(before), '+10:00');
  assert.equal(schedule.offsetLabel(after), '+11:00');
  assert.equal(before.toISOString(), '2026-10-02T23:00:00.000Z');
  assert.equal(after.toISOString(), '2026-10-04T22:00:00.000Z');
});

test('the offset changes back across the April boundary', () => {
  assert.equal(schedule.offsetLabel(schedule.parseLocal('2027-04-03 09:00')), '+11:00');
  assert.equal(schedule.offsetLabel(schedule.parseLocal('2027-04-05 09:00')), '+10:00');
});

test('a round trip returns the same wall clock in both halves of the year', () => {
  for (const local of ['2026-09-19 09:00', '2026-12-19 09:00']) {
    const utc = schedule.parseLocal(local);
    assert.match(schedule.formatLocal(utc), /09:00/, `${local} did not round-trip`);
  }
});

test('a malformed local time is rejected rather than guessed at', () => {
  assert.throws(() => schedule.parseLocal('19/09/2026 9am'), /Expected "YYYY-MM-DD HH:MM"/);
});

// ---------------------------------------------------------------------------
// SCHEDULE.md is generated
// ---------------------------------------------------------------------------

test('SCHEDULE.md carries the do-not-edit marker and derives the offset', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-sched-'));
  const pkgDir = path.join(dir, '2026-11-19-x');
  fs.mkdirSync(pkgDir);
  fs.writeFileSync(path.join(pkgDir, 'publish.json'), JSON.stringify({
    status: 'draft', scheduled_utc: '2026-11-18T22:00:00Z', pillar: 'home', approved_by: null,
  }));
  const out = path.join(dir, 'SCHEDULE.md');
  const text = schedule.generate({ queueDir: dir, outFile: out, now: new Date('2026-09-17T00:00:00Z') });
  assert.match(text, /GENERATED by social\/schedule\.js/);
  assert.match(text, /\+11:00/);
  assert.ok(fs.existsSync(out));
});

// ---------------------------------------------------------------------------
// source_images: three states that must stay three states
// ---------------------------------------------------------------------------

const entry = (slug, source_images) => {
  const pkg = { status: 'draft' };
  if (source_images !== undefined) pkg.source_images = source_images;
  return { slug, pkg };
};

test('two packages sharing a source are caught', () => {
  const res = imagecheck.check([
    entry('a', ['kitchen table flowers']),
    entry('b', ['kitchen table flowers']),
  ], { manifest: new Map() });
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'duplicate');
});

test('an absent source_images is reported, not silently treated as empty', () => {
  const res = imagecheck.check([entry('a', undefined)], { manifest: new Map() });
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'unrecorded');
  assert.match(res.problems[0].message, /not the same as \[\]/);
});

test('an empty source_images passes — a type tile genuinely has no source', () => {
  const res = imagecheck.check([entry('a', []), entry('b', [])], { manifest: new Map() });
  assert.equal(res.ok, true);
  assert.equal(res.typeTiles, 2);
});

test('a rename from spaces to hyphens does not create a second source', () => {
  // The library holds "kitchen table flowers.jpg"; the committed copy is
  // "kitchen-table-flowers.jpg". Keyed literally, those are two sources.
  const res = imagecheck.check([
    entry('a', ['kitchen table flowers']),
    entry('b', ['kitchen-table-flowers.jpg']),
  ], { manifest: new Map() });
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'duplicate');
});

test('the same bytes under two unrelated names are caught via the manifest', () => {
  // New_flowers_1.JPG and P20TS25001.JPG are byte-identical in the real library.
  // Nothing about the names says so, so the hash has to.
  const manifest = new Map([
    ['new-flowers-1', { key: 'new-flowers-1', original_sha256: 'abc123' }],
    ['p20ts25001', { key: 'p20ts25001', original_sha256: 'abc123' }],
  ]);
  const res = imagecheck.check([
    entry('a', ['New_flowers_1']),
    entry('b', ['P20TS25001']),
  ], { manifest });
  assert.equal(res.ok, false);
  assert.equal(res.problems.find((p) => p.kind === 'same-bytes') !== undefined, true);
});

test('different bytes under similar names are not falsely flagged', () => {
  const manifest = new Map([
    ['p20ts25001', { key: 'p20ts25001', original_sha256: 'aaa' }],
    ['p20ts25002', { key: 'p20ts25002', original_sha256: 'bbb' }],
  ]);
  const res = imagecheck.check([
    entry('a', ['P20TS25001']),
    entry('b', ['P20TS25002']),
  ], { manifest });
  assert.equal(res.ok, true);
});

test('the same photograph under two paths or extensions is still one source', () => {
  // The library holds the same file in two Drive folders, and the catalogue
  // holds one design as two files. Keyed on a path, both slip through.
  const res = imagecheck.check([
    entry('a', ['Adelaide/PRINT-HI-5072_115.jpg']),
    entry('b', ['Photos for marketing/print-hi-5072_115.JPG']),
  ], { manifest: new Map() });
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'duplicate');
});

test('a source repeated inside one package is caught', () => {
  const res = imagecheck.check([entry('a', ['x', 'x'])], { manifest: new Map() });
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'repeat-within');
});

test('a clean queue of distinct sources passes', () => {
  const res = imagecheck.check([
    entry('a', ['kitchen table flowers']),
    entry('b', ['P20TS25042']),
    entry('c', []),
  ], { manifest: new Map() });
  assert.equal(res.ok, true);
  assert.equal(res.distinctSources, 2);
  assert.equal(res.typeTiles, 1);
});

test('source_images that is not an array is rejected', () => {
  const res = imagecheck.check([entry('a', 'kitchen table flowers')], { manifest: new Map() });
  assert.equal(res.ok, false);
  assert.equal(res.problems[0].kind, 'malformed');
});

// ---------------------------------------------------------------------------
// Choosing a source
// ---------------------------------------------------------------------------

test('unused() lists library images no package has claimed', () => {
  const manifest = new Map([
    ['a', { key: 'a' }], ['b', { key: 'b' }], ['c', { key: 'c' }],
  ]);
  const entries = [
    { slug: 'p1', pkg: { source_images: ['A.jpg'] } },
    { slug: 'p2', pkg: { source_images: [] } },
  ];
  assert.deepEqual(imagecheck.unused({ manifest, entries }), ['b', 'c']);
});

test('unused() matches regardless of separators or extension', () => {
  const manifest = new Map([['kitchen-table-flowers', { key: 'kitchen-table-flowers' }]]);
  const entries = [{ slug: 'p1', pkg: { source_images: ['kitchen table flowers'] } }];
  assert.deepEqual(imagecheck.unused({ manifest, entries }), []);
});

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const render = require('./render');

test('a centre crop keeps the target aspect and stays inside the source', () => {
  const c = render.centreCrop(2048, 1366, 1080 / 1350);
  assert.equal(c.h, 1366);
  assert.equal(Math.abs(c.w / c.h - 1080 / 1350) < 0.01, true);
  assert.equal(c.x + c.w <= 2048, true);
  assert.equal(c.y + c.h <= 1366, true);
});

test('bias moves the crop window without leaving the frame', () => {
  const left = render.centreCrop(2048, 1366, 4 / 5, 0);
  const right = render.centreCrop(2048, 1366, 4 / 5, 1);
  assert.equal(left.x, 0);
  assert.equal(right.x + right.w, 2048);
});

test('a source outside the library cannot be rendered at all', () => {
  // Structural, not advisory: the seasonal range has no path through this tool.
  assert.throws(
    () => render.findSource('aa-mitchell-seasonal-thing', [{ key: 'kitchen-table-flowers' }]),
    (err) => err instanceof render.RenderError && /not in the library/.test(err.message),
  );
});

test('the real library renders a feed tile at exactly 1080x1350', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-render-'));
  const res = render.render({ source: 'kitchen table flowers', slug: 'x', outRoot: out });
  assert.equal(res.dimensions, '1080x1350');
  assert.match(res.crop, /^\d+x\d+\+\d+\+\d+$/);
  assert.equal(fs.existsSync(path.join(out, 'x', '1.jpg')), true);
});

test('a story renders at 1080x1920 on the brand paper ground', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-render-'));
  const res = render.render({ source: 'kitchen-table-flowers', slug: 'x', aspect: 'story', outRoot: out });
  assert.equal(res.dimensions, '1080x1920');
  assert.equal(path.basename(res.output), 'story.jpg');
});

test('the crop is reported back so the package can record it', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-render-'));
  const res = render.render({ source: 'kitchen-table-flowers', slug: 'x', crop: '100,50,800,1000', outRoot: out });
  assert.equal(res.crop, '800x1000+100+50');
});

test('a crop that falls outside the source is refused', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-render-'));
  assert.throws(
    () => render.render({ source: 'kitchen-table-flowers', slug: 'x', crop: '0,0,9000,9000', outRoot: out }),
    (err) => /falls outside/.test(err.message),
  );
});
